import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthWrapper from "@/lib/next.auth.provider";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "@/theme.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <NextAuthWrapper>{children}</NextAuthWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
