import HeaderWrapper from "@/components/header/header.wrapper";
import BodyWrapper from "@/components/home/body.wrapper";
import {
  DrawerProvider,
  UserProvider,
  WidthScreenProvider,
} from "@/lib/custom.content";
import HomeWrapper from "@/lib/home.wrapper";
import NextAuthWrapper from "@/lib/next.auth.provider";
import "@/style/loading.css";
import theme from "@/theme.js";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import React from "react";
import { authOptions } from "../api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Art Devs Socail",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: User | null = await getServerSession(authOptions);
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <UserProvider>
        <DrawerProvider>
          <WidthScreenProvider>
            {session && (
              <NextAuthWrapper>
                <HeaderWrapper user={session} />
                <HomeWrapper>
                  <BodyWrapper session={session}>{children}</BodyWrapper>
                </HomeWrapper>
              </NextAuthWrapper>
            )}
            {!session && children}
          </WidthScreenProvider>
        </DrawerProvider>
      </UserProvider>
    </ThemeProvider>
  );
  // } else {
  //   return (
  //     <html lang="en">
  //       <body className={inter.className}>
  //         <ThemeProvider theme={theme}>
  //           <CssBaseline />
  //           <UserProvider>{children}</UserProvider>
  //         </ThemeProvider>
  //       </body>
  //     </html>
  //   );
  // }
}
